#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed:
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg      = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = aarch64

# Pacman won't upgrade packages in the IgnorePkg and IgnoreGroup lists below
# when it's installing other packages with pacman -S or it's installing
# replacements with pacman -U. Shell glob patterns are allowed, individual
# items must be separated by whitespace.
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
#NoProgressBar
CheckSpace
#VerbosePkgLists
ParallelDownloads = 5

# By default, pacman accepts packages signed by keys that it knows about.
# As an added security measure, it will also refuse to use a local package
# (i.e., a package not in a repository) unless it is signed with a key that
# is also known to pacman. See pacman(8) and pacman-key(8) for more details
# on key management.
#
# The following options allow users to add security on their own terms
# from weakest to strongest. Note that you must always trust the packager(s)
# upon which your packages depend, in addition to explicitly trusting them below
# with the SigLevel directive. Also note that the optional symlink resolving
# uses packages specified with the SigLevel directive; for example, packages
# needed for symlink resolution will be installed even if packages are signed
# SigLevel for Optional and those packages are not signed.
#
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

#
# REPOSITORIES
#
# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include line. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repository.
#
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[testing]
#Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

#[multilib]
#Include = /etc/pacman.d/mirrorlist
